source_code_url = 'https://github.com/iomintz/Adhesive'

[telegram]
# access api_id and api_hash at https://my.telegram.org/apps
api_id = 123
api_hash = 'deadbeef'
# get this from The BotFather
api_token = '1234:deadbea7cafe'
session_name = 'anon'

[signal]
# signal phone number that you have registered with signald
# if this is not set, the signal bot will not run but everything else will function normally
username = '+xxxxxxxxxxx'

[signal.stickers]
# get these by running `python -m adhesive.signal_auth`
# username is NOT the same as your phone number
username = '...'
password = '...'

# This is your API key for signalstickers.com
# This is optional. If present, a button to submit your converted Signal sticker pack
# to signalstickers.com will be displayed.
signalstickers_api_token = '...'
